version: '2'

services:
  frontend:
    restart: always
    build: ./frontend
    environment:
      PORT: 8081
      RABBITMQ_HOSTNAME: rabbit
    ports:
    - 8081:8081
    links:
    - rabbit
    depends_on:
    - redis
    - rabbit
    - db
    - emailer
    - parser

  db:
    restart: always
    build: ./db
    environment:
      RABBITMQ_HOSTNAME: rabbit
      REDIS_HOST: redis
    links:
    - redis
    - rabbit
    depends_on:
    - redis
    - rabbit

  emailer:
    restart: always
    build: ./emailer
    environment:
      RABBITMQ_HOSTNAME: rabbit
      EMAIL_ADDR: reactive-demo@null.net
    links:
    - rabbit
    depends_on:
    - rabbit

  parser:
    restart: always
    build: ./parser
    environment:
      RABBITMQ_HOSTNAME: rabbit
    links:
    - rabbit
    depends_on:
    - rabbit
    - db

  rabbit:
    image: rabbitmq:3-management
    restart: always
    ports:
    - 5672:5672
    - 15672:15672

  redis:
    image: redis:3.0
    restart: always
    ports:
    - 6379:6379
