apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emailer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: emailer
    spec:
      containers:
      - name: emailer
        image: runnable/reactive-demo:emailer-latest
        env:
        - name: RABBITMQ_HOSTNAME
          value: rabbit
        - name: EMAIL_ADDR
          value: default@gmail.com
